# Generated by Django 3.2.15 on 2022-08-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
