# Generated by Django 3.2.15 on 2022-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_auto_20220822_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='pics1')),
                ('desc1', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name1',
        ),
    ]
