# Generated by Django 3.2.15 on 2022-08-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_auto_20220822_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
